name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  web_and_docs:
    name: Web and docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup env
      run: |
        pip install sphinx
        pip install -e .


