name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  web_and_docs:
    name: Web and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup env
      run: |
        python -m pip install sphinx setuptools
        python -m pip install -e .

    - name: Build documentation
      run: |
        cd docs
        make html

